name: 🚀 Deploy to cPanel via FTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload project to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .
          server-dir: /home/xutsrmxo/apps/NeoTravelFlow/
          exclude: |
            **/.git*
            **/node_modules/**
            **/.next/**
            **/.vscode/**


