name: 🚀 Deploy to cPanel via FTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ViajesCorporativos/APT
          server-dir: /home/xutsrmxo/apps/NeoTravelFlow/
          # Si da problema de conexión, cambia a: protocol: ftp
          protocol: ftps
          exclude: |
            **/.git/**
            **/.github/**
            **/node_modules/**
            **/.next/**
            **/.vscode/**
