name: 🚀 Deploy to cPanel via FTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}         # ej: svbh8910.banahosting.com
          username: ${{ secrets.FTP_USERNAME }}   # ej: deploy@proxyportfolio.space
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp                           # <<< usar ftp
          port: 21                                # <<< puerto estándar ftp
          local-dir: ./ViajesCorporativos/APT/    # carpeta de tu app
          server-dir: /home/xutsrmxo/apps/NeoTravelFlow/
          exclude: |
            **/.git/**
            **/.github/**
            **/node_modules/**
            **/.next/**
            **/.vscode/**
